# Generated by Django 4.1 on 2022-08-14 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.PositiveSmallIntegerField(null=True)),
                ('empid_pic', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('director_mail', models.CharField(max_length=30, null=True)),
                ('registrar_mail', models.CharField(max_length=30, null=True)),
                ('hod_mail', models.CharField(max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='college', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('DOB', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.PositiveSmallIntegerField(default=0, null=True)),
                ('designation', models.CharField(max_length=250)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='apis.collegeinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='VacanciesInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_posting', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.BooleanField(blank=True, default=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('responsibilities', models.CharField(blank=True, max_length=500, null=True)),
                ('qualifications', models.CharField(blank=True, max_length=500, null=True)),
                ('compensation', models.FloatField(null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='apis.collegeinfomodel')),
                ('skills', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyApplicantMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_vacancies', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existing_applicants', to='apis.vacanciesinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='RecuitmentCommitteeInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fifth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fifth_member', to='apis.employeeinfomodel')),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_member', to='apis.employeeinfomodel')),
                ('fourth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_member', to='apis.employeeinfomodel')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_member', to='apis.employeeinfomodel')),
                ('third_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_member', to='apis.employeeinfomodel')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee', to='apis.vacanciesinfomodel')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantQualificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_title', models.CharField(blank=True, max_length=50)),
                ('marks', models.FloatField(null=True)),
                ('passing_year', models.CharField(blank=True, max_length=20)),
                ('institute', models.CharField(max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('full_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('DOB', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, default='Male', max_length=10, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('pincode', models.PositiveSmallIntegerField(default=0, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('marital_status', models.BooleanField(blank=True, null=True)),
                ('phone_number', models.PositiveSmallIntegerField(default=0, null=True)),
                ('total_experience', models.FloatField(default=0, null=True)),
                ('resume', models.CharField(blank=True, max_length=200, null=True)),
                ('skillset', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=20)),
                ('from_date', models.CharField(blank=True, max_length=20)),
                ('to_date', models.CharField(blank=True, max_length=20)),
                ('institute', models.CharField(blank=True, max_length=50)),
                ('details', models.CharField(blank=True, max_length=200)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
