# Generated by Django 4.1 on 2022-08-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinfomodel',
            name='department',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='employeeinfomodel',
            name='empid',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vacancyapplicantmapping',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfomodel',
            name='designation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
